# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=50, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, default=b'+7 (000) 000-00-00', max_length=256, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, default=b'email@mail.com', max_length=128, null=True, verbose_name='E-Mail')),
                ('address', models.CharField(blank=True, max_length=2048, verbose_name='Address')),
                ('www', models.URLField(blank=True, default=b'http://glav.it/', max_length=64, null=True, verbose_name='WWW')),
                ('photo', models.ImageField(blank=True, upload_to=b'img/office', verbose_name='Photo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True, verbose_name='Longitude')),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Center longitude')),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Center latitude')),
                ('zoom', models.PositiveSmallIntegerField(blank=True, default=15, null=True, verbose_name='Zoom')),
                ('order', models.PositiveSmallIntegerField(default=500, verbose_name='Sort order')),
                ('main', models.BooleanField(default=True, verbose_name='Main')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sites', models.ManyToManyField(related_name='offices', to='sites.Site', verbose_name='Sites')),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('email', models.CharField(max_length=128, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('from_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='From name')),
                ('from_email', models.EmailField(max_length=128, verbose_name='From E-Mail')),
                ('email_host', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL HOST')),
                ('email_host_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL HOST USER')),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL HOST PASSWORD')),
                ('email_port', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='EMAIL_PORT')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='EMAIL_USE_TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='EMAIL_USE_SSL')),
                ('email_timeout', models.IntegerField(blank=True, default=None, null=True, verbose_name='EMAIL_TIMEOUT')),
                ('email_ssl_keyfile', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL_SSL_KEYFILE')),
                ('email_ssl_certfile', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL_SSL_CERTFILE')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contacts.Subject', verbose_name='Subject'),
        ),
    ]
