# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('submit_name', models.CharField(max_length=128, verbose_name='Submit bottom name')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Form Config',
                'verbose_name_plural': 'Forms Configs',
            },
        ),
        migrations.CreateModel(
            name='FormLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('referrer', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Referrer')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('form_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.FormConfig', verbose_name='Form Config')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Form log',
                'verbose_name_plural': 'Form logs',
            },
        ),
        migrations.AlterField(
            model_name='office',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True, verbose_name='Center latitude'),
        ),
        migrations.AlterField(
            model_name='office',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True, verbose_name='Center longitude'),
        ),
    ]
