# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160403_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='address_box',
            field=models.CharField(blank=True, help_text='The post office box number for PO box addresses', max_length=256, verbose_name='Post office box number'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_country',
            field=models.CharField(blank=True, max_length=256, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_locality',
            field=models.CharField(blank=True, help_text='Mountain View', max_length=256, verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_postal',
            field=models.CharField(blank=True, max_length=256, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_region',
            field=models.CharField(blank=True, help_text='CA', max_length=256, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_street',
            field=models.CharField(blank=True, help_text='T1600 Amphitheatre Pkwy', max_length=256, verbose_name='Street address'),
        ),
    ]
