# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='field_type',
            field=models.IntegerField(choices=[(1, 'Single line text'), (2, 'Multi line text'), (3, 'Email'), (13, 'Number'), (14, 'URL'), (4, 'Check box'), (5, 'Check boxes'), (6, 'Drop down'), (7, 'Multi select'), (8, 'Radio buttons'), (9, 'File upload'), (10, 'Date'), (11, 'Date/time'), (15, 'Date of birth'), (12, 'Hidden')], default=1, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formfield',
            name='form_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='contacts.FormConfig', verbose_name='Form Config'),
        ),
    ]
