# Generated by Django 2.1.5 on 2019-01-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_formfield_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfig',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='recaptcha_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='reCAPTCHA secret'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='recaptcha_sitekey',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='reCAPTCHA sitekey'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='group',
            field=models.CharField(default='data', max_length=64, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='formlog',
            name='form_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.FormConfig', verbose_name='Form Config'),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.CharField(blank=True, default='email@mail.com', max_length=128, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, default='+7 (000) 000-00-00', max_length=256, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='office',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/office', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='office',
            name='www',
            field=models.URLField(blank=True, default='http://glav.it/', max_length=64, null=True, verbose_name='WWW'),
        ),
        migrations.AlterField(
            model_name='officefeature',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='contacts.Office', verbose_name='Office'),
        ),
    ]
