# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20160403_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('key', models.SlugField(max_length=128, verbose_name='Key')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Value')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='contacts.Office', verbose_name='Office')),
            ],
            options={
                'ordering': ['office', 'name'],
                'verbose_name': 'Office feature',
                'verbose_name_plural': 'Office features',
            },
        ),
    ]
