# Generated by Django 2.1.5 on 2019-01-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20190126_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formconfig',
            old_name='error_message',
            new_name='message_error',
        ),
        migrations.RenameField(
            model_name='formconfig',
            old_name='success_message',
            new_name='message_success',
        ),
    ]
