# Generated by Django 2.1.5 on 2019-01-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20190126_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfig',
            name='recaptcha_group',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='reCAPTCHA group'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='submit_group',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Submit group'),
        ),
    ]
